alter table task add column if not exists short_id integer;

update task t
set short_id = n.rn
from (
    select id, row_number() over (order by created_at asc, id asc) as rn
    from task
) n
where t.id = n.id
  and t.short_id is null;

alter table task alter column short_id set not null;

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'task'
          and column_name = 'short_id'
          and is_identity = 'NO'
    ) then
        alter table task alter column short_id add generated by default as identity;
    end if;
end $$;

select setval(
    pg_get_serial_sequence('task', 'short_id'),
    greatest(coalesce((select max(short_id) from task), 0), 1),
    exists (select 1 from task)
);

create unique index if not exists ux_task_short_id on task (short_id);
